const List<Map> certificates = [
  {
    "organisation": "Great Learning",
    "title": "My SQL Basics",
    "start": "Sept 2024",
    "end": "Nov 2024",
    "link": "https://www.mygreatlearning.com/certificate/NUNXQPCR",
    "skills": "SQL, MySQL, Joins",
  },
  {
    "organisation": "Great Learning",
    "title": "Oracle SQL",
    "start": "Nov 2024",
    "end": "Nov 2024",
    "link": "https://www.mygreatlearning.com/certificate/BZKVXVDU",
    "skills": "SQL, MySQL, Joins",
  },
  {
    "organisation": "Great Learning",
    "title": "Python MySQL",
    "start": "Nov 2024",
    "end": "Nov 2024",
    "link": "https://www.mygreatlearning.com/certificate/FAADEABB",
    "skills": "Python, MySQL, SQL",
  },
  {
    "organisation": "Great Learning",
    "title": "Introduction to JavaScript",
    "start": "Oct 2024",
    "end": "Nov 2024",
    "link": "https://www.mygreatlearning.com/certificate/TKAXRKRO",
    "skills": "Javascript",
  },
  {
    "organisation": "Great Learning",
    "title": "Front End Development - CSS",
    "start": "Nov 2024",
    "end": "Nov 2024",
    "link": "https://www.mygreatlearning.com/certificate/XIANLHKQ",
    "skills": "CSS",
  },
  {
    "organisation": "Great Learning",
    "title": "Front End Development - HTML",
    "start": "Nov 2024",
    "end": "Nov 2024",
    "link": "https://www.mygreatlearning.com/certificate/KCYQXAHY",
    "skills": "HTML",
  },
  {
    "organisation": "Great Learning",
    "title": 'UI/UX for Beginners',
    "start": "Sept 2024",
    "end": "Oct 2024",
    "link": "https://www.mygreatlearning.com/certificate/WTJBXCNW",
    "skills": "Ui/Ux",
  },
  {
    "organisation": "Great Learning",
    "title": "Flutter for Beginners",
    "start": "July 2024",
    "end": "July 2024",
    "link": "https://www.mygreatlearning.com/certificate/IWNDCXUZ",
    "skills": "Flutter",
  },
  {
    "organisation": "Acmegrade",
    "title": "Data Science",
    "start": "Sept 2022",
    "end": "Nov 2022",
    //"link": "",
    "skills": "Python, Excel, Data Analysis",
  },
  {
    "organisation": 'Udemy',
    "title": 'Flutter and Dart',
    "start": "July 2023",
    "end": "Aug 2024",
    "link": "http://ude.my/UC-84b61990-ddd2-4635-ad31-e6d45d95ebd0",
    "skills": "Flutter, Dart, Firebase",
  },
  {
    "organisation": "Udemy",
    "title": "Kotlin Development Masterclass",
    "start": "Aug 2024",
    "end": "Pres",
    //"link": "",
    "skills": "Kotlin, SQL, API, Firebase",
  },
  {
    "organisation": 'Udemy',
    "title": 'Flutter Masterclass',
    "start": "Nov 2024",
    "end": "Pres",
    //"link": "",
    "skills": "Flutter, Dart, Firebase, API",
  },
];
